(ns examples-registry
  (:require [clojure.edn :as edn]
            [clojure.string :as str]))

;; [display-name  joltc-alias  group  description]
;; Single source of truth: bb.edn's :init requires this instead of inlining
;; the vector, and bb.edn's `demos:examples` task reads it too, printing it
;; as EDN for the demo recorder (see scripts/demo_manifest.edn and `bb record`).
;; The recorder itself is an internal tool that is not publicly released; the
;; committed GIFs under docs/demos/ are what readers actually consume.
(def examples
  [["basic-window"      "run"      "core"   "the minimal raylib window + text"]
   ["input-keys"        "input"    "core"   "steer a ball with the arrow keys"]
   ["input-mouse"       "mouse"    "core"   "a ball follows the mouse; click to recolor"]
   ["input-mouse-wheel" "wheel"    "core"   "scroll a box with the mouse wheel"]
   ["camera-2d"         "camera2d" "core"   "a 2D camera over a skyline (struct-by-value)"]
   ["delta-time"        "delta-time" "core" "per-frame vs delta-time movement"]
   ["scissor-test"      "scissor-test" "core" "a scissor rectangle clips a grid"]
   ["basic-screen-manager" "basic-screen-manager" "core" "a LOGO/TITLE/GAMEPLAY/ENDING flow"]
   ["random-values"     "random-values" "core" "a new random value every two seconds"]
   ["bouncing-ball"     "bounce"   "shapes" "a ball bouncing around the window"]
   ["basic-shapes"      "shapes"   "shapes" "shape primitives + an rlgl triangle"]
   ["colors-palette"    "colors"   "shapes" "every named raylib color in a grid"]
   ["gradient"          "gradient" "shapes" "a vertical two-color gradient"]
   ["following-eyes"    "eyes"     "shapes" "two eyes track the mouse"]
   ["starfield"         "stars"    "shapes" "a twinkling starfield"]
   ["logo-raylib"       "logo"     "shapes" "the raylib logo from rectangles + text"]
   ["mouse-trail"       "mouse-trail" "shapes" "a fading trail follows the cursor"]
   ["recursive-tree"    "recursive-tree" "shapes" "a binary fractal tree"]
   ["math-sine-cosine"  "math-sine-cosine" "shapes" "a live unit-circle trig visualization"]
   ["bullet-hell"       "bullet-hell" "shapes" "a rotating bullet spiral"]
   ["triangle-strip"    "triangle-strip" "shapes" "a rainbow strip via rlgl immediate mode"]
   ["collision-area"    "collision-area" "shapes" "AABB collision between two boxes"]
   ["dashed-line"       "dashed-line" "shapes" "a dashed line follows the mouse"]
   ["double-pendulum"   "double-pendulum" "shapes" "chaotic double-pendulum motion + trail"]
   ["kaleidoscope"      "kaleidoscope" "shapes" "strokes mirrored with 6-fold symmetry"]
   ["hilbert-curve"     "hilbert-curve" "shapes" "a rainbow Hilbert space-filling curve"]
   ["camera-2d-mouse-zoom" "camera-2d-mouse-zoom" "core" "zoom toward the cursor, pinning the point under it"]
   ["camera-2d-platformer" "camera-2d-platformer" "core" "five ways a camera can follow a jumping player"]
   ["circle-sector-drawing" "circle-sector-drawing" "shapes" "a sector whose segment count you can starve"]
   ["easings-ball" "easings-ball" "shapes" "slide, swell and fade, one curve each"]
   ["easings-box" "easings-box" "shapes" "drop, flatten, spin, grow, fade: five curves"]
   ["easings-rectangles" "easings-rectangles" "shapes" "a grid easing out in size and rotation at once"]
   ["easings-testbed" "easings-testbed" "shapes" "one curve at a time, plotted and run"]
   ["ellipse-collision" "ellipse-collision" "shapes" "two ellipses that redden when they overlap"]
   ["input-gestures" "input-gestures" "core" "tap, hold, drag and swipe, named as they happen"]
   ["logo-anim" "logo-anim" "shapes" "the raylib logo assembling itself, unsmoothed"]
   ["math-angle-rotation" "math-angle-rotation" "shapes" "fixed spokes + a spinning line"]
   ["font-sizes"        "text"     "text"   "font sizes + MeasureText centering"]
   ["writing-anim"      "writing-anim" "text" "a message types itself out"]
   ["format-text"       "format-text" "text" "padded score + MM:SS timer readouts"]
   ["words-alignment"   "words-alignment" "text" "align a word inside a box (MeasureText)"]
   ["camera-3d"         "camera-3d" "3d" "an orbiting 3D camera (Camera3D by value)"]
   ["waving-cubes"      "waving-cubes" "3d" "an NxN grid of cubes rippling in 3D"]
   ["camera-3d-first-person" "camera-3d-first-person" "3d" "walk a yard of columns in first person"]
   ["tesseract-view"    "tesseract-view" "3d" "a rotating 4D hypercube projected to 2D"]
   ["wireframe-shapes"  "wireframe-shapes" "3d" "pyramid/octahedron/torus/helix in 3D lines"]
   ["random-sequence" "random-sequence" "core" "bars in a shuffled order, each height used once"]
   ["rectangle-advanced" "rectangle-advanced" "shapes" "per-side roundness with a horizontal gradient"]
   ["rlgl-color-wheel" "rlgl-color-wheel" "shapes" "a hue wheel as a triangle fan, per-vertex colour"]
   ["rlgl-solar-system" "rlgl-solar-system" "3d" "Sun/Earth/Moon via the rlgl matrix stack"]
   ["box-collisions"    "box-collisions" "3d" "a player cube colliding with 3D boxes"]
   ["asteroids"         "asteroids" "games" "the classic vector shooter (rotate/thrust/fire)"]
   ["tetris"            "tetris" "games" "the block-stacking puzzle (move/rotate/drop)"]
   ["pong"              "pong" "games" "two-paddle classic, you (W/S) vs a CPU"]
   ["rlgl-triangle" "rlgl-triangle" "shapes" "a Gouraud triangle with draggable corners"]
   ["storage-values" "storage-values" "core" "values that survive a restart, via a file"]
   ["undo-redo" "undo-redo" "core" "move a square, then step back through the history"]
   ["vampire-survivors" "vampire-survivors" "games" "auto-fire survival: move, waves chase you"]
   ["rotating-cube"     "rotating-cube" "3d" "a single cube spinning via the rlgl matrix stack"]
   ["spinning-cubes"    "spinning-cubes" "3d" "a row of cubes each spinning with a phase offset"]
   ["orthographic-projection" "orthographic-projection" "3d" "perspective vs orthographic (SPACE toggles)"]
   ["point-cloud"       "point-cloud" "3d" "~1500 points as tiny rlgl cubes, rotating"]
   ["bouncing-spheres"  "bouncing-spheres" "3d" "spheres bouncing in a 3D box (rl/sphere!)"]
   ["ball-physics"      "ball-physics" "shapes" "2D balls under gravity, SPACE respawns"]
   ["lines-bezier"      "lines-bezier" "shapes" "a cubic Bézier that follows the mouse"]
   ["input-box"         "input-box" "text" "type into a text box (GetCharPressed)"]
   ["snake"             "snake" "games" "the classic snake (arrow keys, grow, don't crash)"]
   ["breakout"          "breakout" "games" "paddle + ball + brick grid (mouse paddle)"]
   ["space-invaders"    "space-invaders" "games" "marching aliens (arrows + SPACE to shoot)"]
   ["flappy-bird"       "flappy-bird" "games" "flap through the pipe gaps (SPACE)"]
   ["game-2048"         "game-2048" "games" "2048: 4x4 tile-merge puzzle (arrow keys)"]
   ["minesweeper"       "minesweeper" "games" "reveal/flag grid (mouse L reveal, R flag)"]
   ["game-of-life"      "game-of-life" "generative" "Conway's Game of Life (SPACE reseeds)"]
   ["boids"             "boids" "generative" "flocking birds (separation/alignment/cohesion)"]
   ["fireworks"         "fireworks" "generative" "rockets + fading particle bursts"]
   ["fourier-epicycles" "fourier-epicycles" "generative" "rotating circles trace a square wave"]
   ["spirograph"        "spirograph" "generative" "animated hypotrochoid roulette curves"]
   ["l-system"          "l-system" "generative" "an L-system fractal plant (grows + regrows)"]
   ["flow-field"        "flow-field" "generative" "particles steered by a flow field (trails)"]
   ["color-wheel"       "color-wheel" "shapes" "an HSV color wheel (rlgl triangle fan)"]
   ["pie-chart"         "pie-chart" "shapes" "labelled pie slices via rl/sector!"]
   ["splines"           "splines" "shapes" "Catmull-Rom / Bezier / B-spline (SPACE cycles)"]
   ["vector-angle"      "vector-angle" "shapes" "the angle between two vectors (arc + readout)"]
   ["easings"           "easings" "shapes" "a grid of balls, each on a different easing curve"]
   ["penrose-tiling"    "penrose-tiling" "shapes" "a P3 Penrose rhombus tiling (deflation)"]
   ["analog-clock"      "analog-clock" "shapes" "a live analog clock (libc local time)"]
   ["digital-clock"     "digital-clock" "shapes" "a seven-segment HH:MM:SS clock (libc time)"]
   ["ring-drawing"      "ring-drawing" "shapes" "an animated annulus via rl/ring!"]
   ["rounded-rectangle" "rounded-rectangle" "shapes" "rounded rects via sector! corners"]
   ["rectangle-scaling" "rectangle-scaling" "shapes" "drag the corner handle to resize a rect"]
   ["lines-drawing"     "lines-drawing" "shapes" "a rotating fan of thick lines (line-ex!)"]
   ["texture-procedural"  "texture-procedural" "textures" "four textures built pixel by pixel"]
   ["texture-tiling"      "texture-tiling" "textures" "one tile repeated across the window"]
   ["render-texture"      "render-texture" "textures" "a scene drawn off-screen, then reused"]
   ["window-letterbox"    "window-letterbox" "core" "a fixed picture letterboxed into the window"]
   ["bunnymark"           "bunnymark" "textures" "the sprite-count benchmark (click to add)"]
   ["window-flags"        "window-flags" "core" "toggle vsync/resizable/topmost live"]
   ["monitor-detector"    "monitor-detector" "core" "every attached display, current one lit"]
   ["clipboard-text"      "clipboard-text" "core" "type, C copies, V pastes"]
   ["clock-of-clocks" "clock-of-clocks" "generative" "six digits spelled by a grid of clock hands"]
   ["input-gamepad"       "input-gamepad" "core" "sticks, triggers and buttons for pad 0"]
   ["input-multitouch"    "input-multitouch" "core" "touch points (the mouse is point 0)"]
   ["input-virtual-controls" "input-virtual-controls" "core" "an on-screen D-pad and action button"]
   ["lorenz-attractor"    "lorenz-attractor" "3d" "the Lorenz attractor traced in 3D"]
   ["dna-helix"           "dna-helix" "3d" "a turning double helix, coloured bases"]
   ["yaw-pitch-roll"      "yaw-pitch-roll" "3d" "the three aircraft rotations in 3D"]
   ["first-person-maze"   "first-person-maze" "3d" "walk a grid maze, with a minimap"]
   ["cellular-automata"   "cellular-automata" "generative" "Wolfram's elementary automata"]
   ["julia-set"           "julia-set" "shaders" "the Julia set, mouse-steered, in a shader"]
   ["mandelbrot-set"      "mandelbrot-set" "shaders" "the Mandelbrot set, zoomable, in a shader"]
   ["raymarching"         "raymarching" "shaders" "a raymarched SDF scene in a shader"]
   ["rounded-rect-shader" "rounded-rect-shader" "shaders" "SDF rounded rects: fill, border, shadow"]
   ["window-should-close" "window-should-close" "core" "close is a question: ESC asks before it exits"]
   ["palette-switch"      "palette-switch" "shaders" "bands recolored by an ivec3 palette"]
   ["shader-hot-reload"   "shader-hot-reload" "shaders" "swap and recompile the GLSL at runtime"]
   ["multi-sampler"       "multi-sampler" "shaders" "two textures blended by a second sampler"]
   ["postprocessing"      "postprocessing" "shaders" "post-process shaders cycled over a scene"]
   ["custom-uniform"      "custom-uniform" "shaders" "a mouse-steered swirl over a scene"]
   ["texture-painting"    "texture-painting" "shaders" "a blank texture painted by a shader"]
   ["helitorus"           "helitorus" "3d"     "a helix wound around a torus, swept into a tube"]
   ["doom"                "doom"      "3d"     "a textured raycaster: one ray per screen column"]
   ["pacman"              "pacman"    "games"  "pac-man, with the classic ghost personalities"]
   ["audio-raw-stream"    "audio-raw-stream" "audio" "arrow keys steer a live sine tone's pitch/pan"]
   ["starfield-effect"    "starfield-effect" "shapes" "flying starfield (wheel=speed, SPACE=mode)"]
   ["world-screen"        "world-screen" "3d" "a 2D label tracks a cube via GetWorldToScreen"]
   ["camera-2d-split-screen" "camera-2d-split-screen" "core" "two players, two cameras, two render textures"]
   ["eratosthenes-sieve"  "eratosthenes-sieve" "shaders" "the Sieve of Eratosthenes, one test per pixel"]
   ["keyboard-testbed"    "keyboard-testbed" "core" "an on-screen ENG-US keyboard, every key lit"]
   ["mouse-painting"      "mouse-painting" "textures" "a paint program on a render-texture canvas"]
   ["input-actions"       "input-actions" "core" "abstract input actions: keyboard + gamepad"]
   ["particles"           "particles" "generative" "water/smoke/fire particles follow the mouse"]
   ["particles-blending"  "particles-blending" "textures" "200 sparks trail the mouse, alpha vs additive"]
   ["smooth-pixelperfect" "smooth-pixelperfect" "core" "sub-pixel camera smoothing at 5x upscale"]
   ["viewport-scaling"    "viewport-scaling" "core" "6 viewport-scaling policies, resize live"]
   ["geometric-shapes"    "geometric-shapes" "3d"   "cubes, spheres, cylinders, cones, capsules"]
   ["camera-3d-split-screen" "camera-3d-split-screen" "3d" "two players, two render-texture halves"]
   ["rectangle-bounds"    "rectangle-bounds" "text" "draggable word-wrap text container"]
   ["polygon-drawing"     "polygon-drawing" "textures" "hue-wheel texture on a spinning polygon"]
   ["texture-rendering"   "texture-rendering" "shaders" "a grid of squares painted entirely by a shader"]
   ["texture-waves"       "texture-waves" "shaders" "a starfield rippled by a UV-displacement shader"]
   ["srcrec-dstrec"       "srcrec-dstrec" "textures" "srcrec picks the frame, dstrec scales+spins it"]
   ["amp-envelope"        "amp-envelope" "audio" "ADSR amplitude envelope on a 440Hz tone"]])

(def by-name (into {} (map (fn [row] [(nth row 0) row]) examples)))

(defn print-row [row]
  (println (format "  bb %-18s %s" (nth row 0) (nth row 3))))

;; deps.edn's :aliases, read once at namespace load. src-path resolves each
;; joltc alias's ACTUAL launched namespace from here rather than guessing
;; from the alias string. See the file-header note on the :run -> core
;; exception.
(def ^:private deps-aliases
  (:aliases (edn/read-string (slurp "deps.edn"))))

(defn- ns->src-path [ns-str]
  (str "src/" (-> ns-str (str/replace "." "/") (str/replace "-" "_")) ".clj"))

(defn src-path
  "The example's source file path, derived from deps.edn's :main-opts for
   this joltc alias (NOT from the alias string, most aliases equal the
   launched namespace's last segment, but \"run\" -> net.b12n.raylib-jlt.core is
   a verified exception). E.g. \"bounce\" -> \"src/net/b12n/raylib_jlt/bounce.clj\"."
  [alias]
  (let [main-opts (:main-opts (get deps-aliases (keyword alias)))
        ns-str    (str (second main-opts))]
    (ns->src-path ns-str)))
