;; GENERATED FILE. Do not edit by hand.
;; Produced by scripts/gen_aggregator.clj -- regenerate with `bb gen:all`
;; (repo root) or `bb gen:all` from lib/. `bb check:aggregator` fails if this
;; file no longer matches what the generator produces from the 19 concrete
;; module namespaces.
;;
;; 445 public vars total across 19 modules, zero name collisions,
;; computed by asking a live jolt process for each module's ns-publics -- the
;; same mechanism P0.T1's probe proved for def re-export + alter-meta! metadata
;; copy, not a parse of the module source text.
(ns net.b12n.raylib.all
  "Every public var of this library's 445 concrete-module surface, re-exported
  under net.b12n.raylib.all so a caller can (:require [net.b12n.raylib.all :as rl])
  and keep calling rl/rect! instead of requiring all 19 modules by hand.
  net.b12n.raylib.check is not aggregated: it is the library's own headless load
  gate, not part of its public surface.

  173 of these vars carry ^:const in their source module (the raylib/rlgl enum
  families: KEY-*, MOUSE-*, PAD-*, GESTURE-*, AXIS-*, FLAG-*, BLEND-*, UNIFORM-*,
  RL-*, PIXELFORMAT-*, and log's LOG-*/TRACE-LOG-BUFFER). alter-meta! below copies
  :const alongside :doc and :arglists onto every alias, so it is not lost the way
  the hand-written shim this file replaces silently dropped it. The value read
  through the alias is correct either way; :const only affects whether a caller's
  own compile can inline the constant at the call site."
  (:refer-clojure :exclude [run!]) ; core/run! shadows clojure.core/run!
  (:require
   [net.b12n.raylib.audio :as audio]
   [net.b12n.raylib.camera :as camera]
   [net.b12n.raylib.color :as color]
   [net.b12n.raylib.core :as core]
   [net.b12n.raylib.files :as files]
   [net.b12n.raylib.images :as images]
   [net.b12n.raylib.input :as input]
   [net.b12n.raylib.kwargs :as kwargs]
   [net.b12n.raylib.log :as log]
   [net.b12n.raylib.models :as models]
   [net.b12n.raylib.native :as native]
   [net.b12n.raylib.rays :as rays]
   [net.b12n.raylib.rlgl :as rlgl]
   [net.b12n.raylib.shaders :as shaders]
   [net.b12n.raylib.shapes :as shapes]
   [net.b12n.raylib.splines :as splines]
   [net.b12n.raylib.text :as text]
   [net.b12n.raylib.textures :as textures]
   [net.b12n.raylib.util :as util]))

;; --- audio (11) ---------------------------------------------------------
(def audio-stream-processed? audio/audio-stream-processed?)
(alter-meta! #'audio-stream-processed? merge (select-keys (meta #'audio/audio-stream-processed?) [:doc :arglists :const]))
(def clear-audio-stream-callback! audio/clear-audio-stream-callback!)
(alter-meta! #'clear-audio-stream-callback! merge (select-keys (meta #'audio/clear-audio-stream-callback!) [:doc :arglists :const]))
(def close-audio-device audio/close-audio-device)
(alter-meta! #'close-audio-device merge (select-keys (meta #'audio/close-audio-device) [:doc :arglists :const]))
(def init-audio-device audio/init-audio-device)
(alter-meta! #'init-audio-device merge (select-keys (meta #'audio/init-audio-device) [:doc :arglists :const]))
(def load-audio-stream audio/load-audio-stream)
(alter-meta! #'load-audio-stream merge (select-keys (meta #'audio/load-audio-stream) [:doc :arglists :const]))
(def on-audio-stream! audio/on-audio-stream!)
(alter-meta! #'on-audio-stream! merge (select-keys (meta #'audio/on-audio-stream!) [:doc :arglists :const]))
(def play-audio-stream audio/play-audio-stream)
(alter-meta! #'play-audio-stream merge (select-keys (meta #'audio/play-audio-stream) [:doc :arglists :const]))
(def set-audio-stream-buffer-size-default audio/set-audio-stream-buffer-size-default)
(alter-meta! #'set-audio-stream-buffer-size-default merge (select-keys (meta #'audio/set-audio-stream-buffer-size-default) [:doc :arglists :const]))
(def set-audio-stream-pan audio/set-audio-stream-pan)
(alter-meta! #'set-audio-stream-pan merge (select-keys (meta #'audio/set-audio-stream-pan) [:doc :arglists :const]))
(def unload-audio-stream audio/unload-audio-stream)
(alter-meta! #'unload-audio-stream merge (select-keys (meta #'audio/unload-audio-stream) [:doc :arglists :const]))
(def update-audio-stream audio/update-audio-stream)
(alter-meta! #'update-audio-stream merge (select-keys (meta #'audio/update-audio-stream) [:doc :arglists :const]))

;; --- camera (17) --------------------------------------------------------
(def CAMERA-CUSTOM camera/CAMERA-CUSTOM)
(alter-meta! #'CAMERA-CUSTOM merge (select-keys (meta #'camera/CAMERA-CUSTOM) [:doc :arglists :const]))
(def CAMERA-FIRST-PERSON camera/CAMERA-FIRST-PERSON)
(alter-meta! #'CAMERA-FIRST-PERSON merge (select-keys (meta #'camera/CAMERA-FIRST-PERSON) [:doc :arglists :const]))
(def CAMERA-FREE camera/CAMERA-FREE)
(alter-meta! #'CAMERA-FREE merge (select-keys (meta #'camera/CAMERA-FREE) [:doc :arglists :const]))
(def CAMERA-ORBITAL camera/CAMERA-ORBITAL)
(alter-meta! #'CAMERA-ORBITAL merge (select-keys (meta #'camera/CAMERA-ORBITAL) [:doc :arglists :const]))
(def CAMERA-THIRD-PERSON camera/CAMERA-THIRD-PERSON)
(alter-meta! #'CAMERA-THIRD-PERSON merge (select-keys (meta #'camera/CAMERA-THIRD-PERSON) [:doc :arglists :const]))
(def begin-mode-3d-ptr camera/begin-mode-3d-ptr)
(alter-meta! #'begin-mode-3d-ptr merge (select-keys (meta #'camera/begin-mode-3d-ptr) [:doc :arglists :const]))
(def camera3d-alloc camera/camera3d-alloc)
(alter-meta! #'camera3d-alloc merge (select-keys (meta #'camera/camera3d-alloc) [:doc :arglists :const]))
(def camera3d-free! camera/camera3d-free!)
(alter-meta! #'camera3d-free! merge (select-keys (meta #'camera/camera3d-free!) [:doc :arglists :const]))
(def camera3d-set-target! camera/camera3d-set-target!)
(alter-meta! #'camera3d-set-target! merge (select-keys (meta #'camera/camera3d-set-target!) [:doc :arglists :const]))
(def disable-cursor! camera/disable-cursor!)
(alter-meta! #'disable-cursor! merge (select-keys (meta #'camera/disable-cursor!) [:doc :arglists :const]))
(def enable-cursor! camera/enable-cursor!)
(alter-meta! #'enable-cursor! merge (select-keys (meta #'camera/enable-cursor!) [:doc :arglists :const]))
(def end-mode-2d camera/end-mode-2d)
(alter-meta! #'end-mode-2d merge (select-keys (meta #'camera/end-mode-2d) [:doc :arglists :const]))
(def end-mode-3d camera/end-mode-3d)
(alter-meta! #'end-mode-3d merge (select-keys (meta #'camera/end-mode-3d) [:doc :arglists :const]))
(def update-camera! camera/update-camera!)
(alter-meta! #'update-camera! merge (select-keys (meta #'camera/update-camera!) [:doc :arglists :const]))
(def with-camera-2d camera/with-camera-2d)
(alter-meta! #'with-camera-2d merge (select-keys (meta #'camera/with-camera-2d) [:doc :arglists :const]))
(def with-camera-3d camera/with-camera-3d)
(alter-meta! #'with-camera-3d merge (select-keys (meta #'camera/with-camera-3d) [:doc :arglists :const]))
(def world-to-screen camera/world-to-screen)
(alter-meta! #'world-to-screen merge (select-keys (meta #'camera/world-to-screen) [:doc :arglists :const]))

;; --- color (26) ---------------------------------------------------------
(def BEIGE color/BEIGE)
(alter-meta! #'BEIGE merge (select-keys (meta #'color/BEIGE) [:doc :arglists :const]))
(def BLACK color/BLACK)
(alter-meta! #'BLACK merge (select-keys (meta #'color/BLACK) [:doc :arglists :const]))
(def BLUE color/BLUE)
(alter-meta! #'BLUE merge (select-keys (meta #'color/BLUE) [:doc :arglists :const]))
(def BROWN color/BROWN)
(alter-meta! #'BROWN merge (select-keys (meta #'color/BROWN) [:doc :arglists :const]))
(def DARKBLUE color/DARKBLUE)
(alter-meta! #'DARKBLUE merge (select-keys (meta #'color/DARKBLUE) [:doc :arglists :const]))
(def DARKBROWN color/DARKBROWN)
(alter-meta! #'DARKBROWN merge (select-keys (meta #'color/DARKBROWN) [:doc :arglists :const]))
(def DARKGRAY color/DARKGRAY)
(alter-meta! #'DARKGRAY merge (select-keys (meta #'color/DARKGRAY) [:doc :arglists :const]))
(def DARKGREEN color/DARKGREEN)
(alter-meta! #'DARKGREEN merge (select-keys (meta #'color/DARKGREEN) [:doc :arglists :const]))
(def DARKPURPLE color/DARKPURPLE)
(alter-meta! #'DARKPURPLE merge (select-keys (meta #'color/DARKPURPLE) [:doc :arglists :const]))
(def GOLD color/GOLD)
(alter-meta! #'GOLD merge (select-keys (meta #'color/GOLD) [:doc :arglists :const]))
(def GRAY color/GRAY)
(alter-meta! #'GRAY merge (select-keys (meta #'color/GRAY) [:doc :arglists :const]))
(def GREEN color/GREEN)
(alter-meta! #'GREEN merge (select-keys (meta #'color/GREEN) [:doc :arglists :const]))
(def LIGHTGRAY color/LIGHTGRAY)
(alter-meta! #'LIGHTGRAY merge (select-keys (meta #'color/LIGHTGRAY) [:doc :arglists :const]))
(def LIME color/LIME)
(alter-meta! #'LIME merge (select-keys (meta #'color/LIME) [:doc :arglists :const]))
(def MAGENTA color/MAGENTA)
(alter-meta! #'MAGENTA merge (select-keys (meta #'color/MAGENTA) [:doc :arglists :const]))
(def MAROON color/MAROON)
(alter-meta! #'MAROON merge (select-keys (meta #'color/MAROON) [:doc :arglists :const]))
(def ORANGE color/ORANGE)
(alter-meta! #'ORANGE merge (select-keys (meta #'color/ORANGE) [:doc :arglists :const]))
(def PINK color/PINK)
(alter-meta! #'PINK merge (select-keys (meta #'color/PINK) [:doc :arglists :const]))
(def PURPLE color/PURPLE)
(alter-meta! #'PURPLE merge (select-keys (meta #'color/PURPLE) [:doc :arglists :const]))
(def RAYWHITE color/RAYWHITE)
(alter-meta! #'RAYWHITE merge (select-keys (meta #'color/RAYWHITE) [:doc :arglists :const]))
(def RED color/RED)
(alter-meta! #'RED merge (select-keys (meta #'color/RED) [:doc :arglists :const]))
(def SKYBLUE color/SKYBLUE)
(alter-meta! #'SKYBLUE merge (select-keys (meta #'color/SKYBLUE) [:doc :arglists :const]))
(def VIOLET color/VIOLET)
(alter-meta! #'VIOLET merge (select-keys (meta #'color/VIOLET) [:doc :arglists :const]))
(def WHITE color/WHITE)
(alter-meta! #'WHITE merge (select-keys (meta #'color/WHITE) [:doc :arglists :const]))
(def YELLOW color/YELLOW)
(alter-meta! #'YELLOW merge (select-keys (meta #'color/YELLOW) [:doc :arglists :const]))
(def rgba color/rgba)
(alter-meta! #'rgba merge (select-keys (meta #'color/rgba) [:doc :arglists :const]))

;; --- core (41) ----------------------------------------------------------
(def FLAG-MSAA-4X-HINT core/FLAG-MSAA-4X-HINT)
(alter-meta! #'FLAG-MSAA-4X-HINT merge (select-keys (meta #'core/FLAG-MSAA-4X-HINT) [:doc :arglists :const]))
(def FLAG-VSYNC-HINT core/FLAG-VSYNC-HINT)
(alter-meta! #'FLAG-VSYNC-HINT merge (select-keys (meta #'core/FLAG-VSYNC-HINT) [:doc :arglists :const]))
(def FLAG-WINDOW-HIGHDPI core/FLAG-WINDOW-HIGHDPI)
(alter-meta! #'FLAG-WINDOW-HIGHDPI merge (select-keys (meta #'core/FLAG-WINDOW-HIGHDPI) [:doc :arglists :const]))
(def FLAG-WINDOW-RESIZABLE core/FLAG-WINDOW-RESIZABLE)
(alter-meta! #'FLAG-WINDOW-RESIZABLE merge (select-keys (meta #'core/FLAG-WINDOW-RESIZABLE) [:doc :arglists :const]))
(def FLAG-WINDOW-TOPMOST core/FLAG-WINDOW-TOPMOST)
(alter-meta! #'FLAG-WINDOW-TOPMOST merge (select-keys (meta #'core/FLAG-WINDOW-TOPMOST) [:doc :arglists :const]))
(def FLAG-WINDOW-UNDECORATED core/FLAG-WINDOW-UNDECORATED)
(alter-meta! #'FLAG-WINDOW-UNDECORATED merge (select-keys (meta #'core/FLAG-WINDOW-UNDECORATED) [:doc :arglists :const]))
(def begin-drawing core/begin-drawing)
(alter-meta! #'begin-drawing merge (select-keys (meta #'core/begin-drawing) [:doc :arglists :const]))
(def begin-scissor-mode core/begin-scissor-mode)
(alter-meta! #'begin-scissor-mode merge (select-keys (meta #'core/begin-scissor-mode) [:doc :arglists :const]))
(def clear-background core/clear-background)
(alter-meta! #'clear-background merge (select-keys (meta #'core/clear-background) [:doc :arglists :const]))
(def clear-window-state core/clear-window-state)
(alter-meta! #'clear-window-state merge (select-keys (meta #'core/clear-window-state) [:doc :arglists :const]))
(def close-window core/close-window)
(alter-meta! #'close-window merge (select-keys (meta #'core/close-window) [:doc :arglists :const]))
(def end-drawing core/end-drawing)
(alter-meta! #'end-drawing merge (select-keys (meta #'core/end-drawing) [:doc :arglists :const]))
(def end-scissor-mode core/end-scissor-mode)
(alter-meta! #'end-scissor-mode merge (select-keys (meta #'core/end-scissor-mode) [:doc :arglists :const]))
(def get-clipboard-text core/get-clipboard-text)
(alter-meta! #'get-clipboard-text merge (select-keys (meta #'core/get-clipboard-text) [:doc :arglists :const]))
(def get-current-monitor core/get-current-monitor)
(alter-meta! #'get-current-monitor merge (select-keys (meta #'core/get-current-monitor) [:doc :arglists :const]))
(def get-frame-time core/get-frame-time)
(alter-meta! #'get-frame-time merge (select-keys (meta #'core/get-frame-time) [:doc :arglists :const]))
(def get-monitor-count core/get-monitor-count)
(alter-meta! #'get-monitor-count merge (select-keys (meta #'core/get-monitor-count) [:doc :arglists :const]))
(def get-monitor-height core/get-monitor-height)
(alter-meta! #'get-monitor-height merge (select-keys (meta #'core/get-monitor-height) [:doc :arglists :const]))
(def get-monitor-name core/get-monitor-name)
(alter-meta! #'get-monitor-name merge (select-keys (meta #'core/get-monitor-name) [:doc :arglists :const]))
(def get-monitor-refresh-rate core/get-monitor-refresh-rate)
(alter-meta! #'get-monitor-refresh-rate merge (select-keys (meta #'core/get-monitor-refresh-rate) [:doc :arglists :const]))
(def get-monitor-width core/get-monitor-width)
(alter-meta! #'get-monitor-width merge (select-keys (meta #'core/get-monitor-width) [:doc :arglists :const]))
(def get-screen-height core/get-screen-height)
(alter-meta! #'get-screen-height merge (select-keys (meta #'core/get-screen-height) [:doc :arglists :const]))
(def get-screen-width core/get-screen-width)
(alter-meta! #'get-screen-width merge (select-keys (meta #'core/get-screen-width) [:doc :arglists :const]))
(def get-time core/get-time)
(alter-meta! #'get-time merge (select-keys (meta #'core/get-time) [:doc :arglists :const]))
(def get-window-position core/get-window-position)
(alter-meta! #'get-window-position merge (select-keys (meta #'core/get-window-position) [:doc :arglists :const]))
(def get-window-scale-dpi core/get-window-scale-dpi)
(alter-meta! #'get-window-scale-dpi merge (select-keys (meta #'core/get-window-scale-dpi) [:doc :arglists :const]))
(def init-window core/init-window)
(alter-meta! #'init-window merge (select-keys (meta #'core/init-window) [:doc :arglists :const]))
(def run! core/run!)
(alter-meta! #'run! merge (select-keys (meta #'core/run!) [:doc :arglists :const]))
(def set-clipboard-text core/set-clipboard-text)
(alter-meta! #'set-clipboard-text merge (select-keys (meta #'core/set-clipboard-text) [:doc :arglists :const]))
(def set-config-flags core/set-config-flags)
(alter-meta! #'set-config-flags merge (select-keys (meta #'core/set-config-flags) [:doc :arglists :const]))
(def set-exit-key core/set-exit-key)
(alter-meta! #'set-exit-key merge (select-keys (meta #'core/set-exit-key) [:doc :arglists :const]))
(def set-target-fps core/set-target-fps)
(alter-meta! #'set-target-fps merge (select-keys (meta #'core/set-target-fps) [:doc :arglists :const]))
(def set-window-min-size core/set-window-min-size)
(alter-meta! #'set-window-min-size merge (select-keys (meta #'core/set-window-min-size) [:doc :arglists :const]))
(def set-window-monitor core/set-window-monitor)
(alter-meta! #'set-window-monitor merge (select-keys (meta #'core/set-window-monitor) [:doc :arglists :const]))
(def set-window-state core/set-window-state)
(alter-meta! #'set-window-state merge (select-keys (meta #'core/set-window-state) [:doc :arglists :const]))
(def take-screenshot core/take-screenshot)
(alter-meta! #'take-screenshot merge (select-keys (meta #'core/take-screenshot) [:doc :arglists :const]))
(def toggle-borderless-windowed! core/toggle-borderless-windowed!)
(alter-meta! #'toggle-borderless-windowed! merge (select-keys (meta #'core/toggle-borderless-windowed!) [:doc :arglists :const]))
(def toggle-fullscreen core/toggle-fullscreen)
(alter-meta! #'toggle-fullscreen merge (select-keys (meta #'core/toggle-fullscreen) [:doc :arglists :const]))
(def window-resized? core/window-resized?)
(alter-meta! #'window-resized? merge (select-keys (meta #'core/window-resized?) [:doc :arglists :const]))
(def window-should-close? core/window-should-close?)
(alter-meta! #'window-should-close? merge (select-keys (meta #'core/window-should-close?) [:doc :arglists :const]))
(def window-state? core/window-state?)
(alter-meta! #'window-state? merge (select-keys (meta #'core/window-state?) [:doc :arglists :const]))

;; --- files (7) ---------------------------------------------------------
(def directory-exists? files/directory-exists?)
(alter-meta! #'directory-exists? merge (select-keys (meta #'files/directory-exists?) [:doc :arglists :const]))
(def directory-files files/directory-files)
(alter-meta! #'directory-files merge (select-keys (meta #'files/directory-files) [:doc :arglists :const]))
(def dropped-files files/dropped-files)
(alter-meta! #'dropped-files merge (select-keys (meta #'files/dropped-files) [:doc :arglists :const]))
(def file-dropped? files/file-dropped?)
(alter-meta! #'file-dropped? merge (select-keys (meta #'files/file-dropped?) [:doc :arglists :const]))
(def get-file-name files/get-file-name)
(alter-meta! #'get-file-name merge (select-keys (meta #'files/get-file-name) [:doc :arglists :const]))
(def get-prev-directory-path files/get-prev-directory-path)
(alter-meta! #'get-prev-directory-path merge (select-keys (meta #'files/get-prev-directory-path) [:doc :arglists :const]))
(def get-working-directory files/get-working-directory)
(alter-meta! #'get-working-directory merge (select-keys (meta #'files/get-working-directory) [:doc :arglists :const]))

;; --- images (25) --------------------------------------------------------
(def image->texture images/image->texture)
(alter-meta! #'image->texture merge (select-keys (meta #'images/image->texture) [:doc :arglists :const]))
(def image-blur-gaussian! images/image-blur-gaussian!)
(alter-meta! #'image-blur-gaussian! merge (select-keys (meta #'images/image-blur-gaussian!) [:doc :arglists :const]))
(def image-cellular images/image-cellular)
(alter-meta! #'image-cellular merge (select-keys (meta #'images/image-cellular) [:doc :arglists :const]))
(def image-checked images/image-checked)
(alter-meta! #'image-checked merge (select-keys (meta #'images/image-checked) [:doc :arglists :const]))
(def image-color images/image-color)
(alter-meta! #'image-color merge (select-keys (meta #'images/image-color) [:doc :arglists :const]))
(def image-color-brightness! images/image-color-brightness!)
(alter-meta! #'image-color-brightness! merge (select-keys (meta #'images/image-color-brightness!) [:doc :arglists :const]))
(def image-color-contrast! images/image-color-contrast!)
(alter-meta! #'image-color-contrast! merge (select-keys (meta #'images/image-color-contrast!) [:doc :arglists :const]))
(def image-color-grayscale! images/image-color-grayscale!)
(alter-meta! #'image-color-grayscale! merge (select-keys (meta #'images/image-color-grayscale!) [:doc :arglists :const]))
(def image-color-invert! images/image-color-invert!)
(alter-meta! #'image-color-invert! merge (select-keys (meta #'images/image-color-invert!) [:doc :arglists :const]))
(def image-color-tint! images/image-color-tint!)
(alter-meta! #'image-color-tint! merge (select-keys (meta #'images/image-color-tint!) [:doc :arglists :const]))
(def image-convolve! images/image-convolve!)
(alter-meta! #'image-convolve! merge (select-keys (meta #'images/image-convolve!) [:doc :arglists :const]))
(def image-copy! images/image-copy!)
(alter-meta! #'image-copy! merge (select-keys (meta #'images/image-copy!) [:doc :arglists :const]))
(def image-crop! images/image-crop!)
(alter-meta! #'image-crop! merge (select-keys (meta #'images/image-crop!) [:doc :arglists :const]))
(def image-flip-horizontal! images/image-flip-horizontal!)
(alter-meta! #'image-flip-horizontal! merge (select-keys (meta #'images/image-flip-horizontal!) [:doc :arglists :const]))
(def image-flip-vertical! images/image-flip-vertical!)
(alter-meta! #'image-flip-vertical! merge (select-keys (meta #'images/image-flip-vertical!) [:doc :arglists :const]))
(def image-format! images/image-format!)
(alter-meta! #'image-format! merge (select-keys (meta #'images/image-format!) [:doc :arglists :const]))
(def image-from-texture! images/image-from-texture!)
(alter-meta! #'image-from-texture! merge (select-keys (meta #'images/image-from-texture!) [:doc :arglists :const]))
(def image-gradient-linear images/image-gradient-linear)
(alter-meta! #'image-gradient-linear merge (select-keys (meta #'images/image-gradient-linear) [:doc :arglists :const]))
(def image-gradient-radial images/image-gradient-radial)
(alter-meta! #'image-gradient-radial merge (select-keys (meta #'images/image-gradient-radial) [:doc :arglists :const]))
(def image-gradient-square images/image-gradient-square)
(alter-meta! #'image-gradient-square merge (select-keys (meta #'images/image-gradient-square) [:doc :arglists :const]))
(def image-perlin-noise images/image-perlin-noise)
(alter-meta! #'image-perlin-noise merge (select-keys (meta #'images/image-perlin-noise) [:doc :arglists :const]))
(def image-resize! images/image-resize!)
(alter-meta! #'image-resize! merge (select-keys (meta #'images/image-resize!) [:doc :arglists :const]))
(def image-text images/image-text)
(alter-meta! #'image-text merge (select-keys (meta #'images/image-text) [:doc :arglists :const]))
(def image-white-noise images/image-white-noise)
(alter-meta! #'image-white-noise merge (select-keys (meta #'images/image-white-noise) [:doc :arglists :const]))
(def unload-image! images/unload-image!)
(alter-meta! #'unload-image! merge (select-keys (meta #'images/unload-image!) [:doc :arglists :const]))

;; --- input (147) ---------------------------------------------------------
(def AXIS-LEFT-X input/AXIS-LEFT-X)
(alter-meta! #'AXIS-LEFT-X merge (select-keys (meta #'input/AXIS-LEFT-X) [:doc :arglists :const]))
(def AXIS-LEFT-Y input/AXIS-LEFT-Y)
(alter-meta! #'AXIS-LEFT-Y merge (select-keys (meta #'input/AXIS-LEFT-Y) [:doc :arglists :const]))
(def AXIS-RIGHT-X input/AXIS-RIGHT-X)
(alter-meta! #'AXIS-RIGHT-X merge (select-keys (meta #'input/AXIS-RIGHT-X) [:doc :arglists :const]))
(def AXIS-RIGHT-Y input/AXIS-RIGHT-Y)
(alter-meta! #'AXIS-RIGHT-Y merge (select-keys (meta #'input/AXIS-RIGHT-Y) [:doc :arglists :const]))
(def GESTURE-DOUBLETAP input/GESTURE-DOUBLETAP)
(alter-meta! #'GESTURE-DOUBLETAP merge (select-keys (meta #'input/GESTURE-DOUBLETAP) [:doc :arglists :const]))
(def GESTURE-DRAG input/GESTURE-DRAG)
(alter-meta! #'GESTURE-DRAG merge (select-keys (meta #'input/GESTURE-DRAG) [:doc :arglists :const]))
(def GESTURE-HOLD input/GESTURE-HOLD)
(alter-meta! #'GESTURE-HOLD merge (select-keys (meta #'input/GESTURE-HOLD) [:doc :arglists :const]))
(def GESTURE-NONE input/GESTURE-NONE)
(alter-meta! #'GESTURE-NONE merge (select-keys (meta #'input/GESTURE-NONE) [:doc :arglists :const]))
(def GESTURE-PINCH-IN input/GESTURE-PINCH-IN)
(alter-meta! #'GESTURE-PINCH-IN merge (select-keys (meta #'input/GESTURE-PINCH-IN) [:doc :arglists :const]))
(def GESTURE-PINCH-OUT input/GESTURE-PINCH-OUT)
(alter-meta! #'GESTURE-PINCH-OUT merge (select-keys (meta #'input/GESTURE-PINCH-OUT) [:doc :arglists :const]))
(def GESTURE-SWIPE-DOWN input/GESTURE-SWIPE-DOWN)
(alter-meta! #'GESTURE-SWIPE-DOWN merge (select-keys (meta #'input/GESTURE-SWIPE-DOWN) [:doc :arglists :const]))
(def GESTURE-SWIPE-LEFT input/GESTURE-SWIPE-LEFT)
(alter-meta! #'GESTURE-SWIPE-LEFT merge (select-keys (meta #'input/GESTURE-SWIPE-LEFT) [:doc :arglists :const]))
(def GESTURE-SWIPE-RIGHT input/GESTURE-SWIPE-RIGHT)
(alter-meta! #'GESTURE-SWIPE-RIGHT merge (select-keys (meta #'input/GESTURE-SWIPE-RIGHT) [:doc :arglists :const]))
(def GESTURE-SWIPE-UP input/GESTURE-SWIPE-UP)
(alter-meta! #'GESTURE-SWIPE-UP merge (select-keys (meta #'input/GESTURE-SWIPE-UP) [:doc :arglists :const]))
(def GESTURE-TAP input/GESTURE-TAP)
(alter-meta! #'GESTURE-TAP merge (select-keys (meta #'input/GESTURE-TAP) [:doc :arglists :const]))
(def KEY-A input/KEY-A)
(alter-meta! #'KEY-A merge (select-keys (meta #'input/KEY-A) [:doc :arglists :const]))
(def KEY-APOSTROPHE input/KEY-APOSTROPHE)
(alter-meta! #'KEY-APOSTROPHE merge (select-keys (meta #'input/KEY-APOSTROPHE) [:doc :arglists :const]))
(def KEY-B input/KEY-B)
(alter-meta! #'KEY-B merge (select-keys (meta #'input/KEY-B) [:doc :arglists :const]))
(def KEY-BACKSLASH input/KEY-BACKSLASH)
(alter-meta! #'KEY-BACKSLASH merge (select-keys (meta #'input/KEY-BACKSLASH) [:doc :arglists :const]))
(def KEY-BACKSPACE input/KEY-BACKSPACE)
(alter-meta! #'KEY-BACKSPACE merge (select-keys (meta #'input/KEY-BACKSPACE) [:doc :arglists :const]))
(def KEY-C input/KEY-C)
(alter-meta! #'KEY-C merge (select-keys (meta #'input/KEY-C) [:doc :arglists :const]))
(def KEY-CAPS-LOCK input/KEY-CAPS-LOCK)
(alter-meta! #'KEY-CAPS-LOCK merge (select-keys (meta #'input/KEY-CAPS-LOCK) [:doc :arglists :const]))
(def KEY-COMMA input/KEY-COMMA)
(alter-meta! #'KEY-COMMA merge (select-keys (meta #'input/KEY-COMMA) [:doc :arglists :const]))
(def KEY-D input/KEY-D)
(alter-meta! #'KEY-D merge (select-keys (meta #'input/KEY-D) [:doc :arglists :const]))
(def KEY-DELETE input/KEY-DELETE)
(alter-meta! #'KEY-DELETE merge (select-keys (meta #'input/KEY-DELETE) [:doc :arglists :const]))
(def KEY-DOWN input/KEY-DOWN)
(alter-meta! #'KEY-DOWN merge (select-keys (meta #'input/KEY-DOWN) [:doc :arglists :const]))
(def KEY-E input/KEY-E)
(alter-meta! #'KEY-E merge (select-keys (meta #'input/KEY-E) [:doc :arglists :const]))
(def KEY-EIGHT input/KEY-EIGHT)
(alter-meta! #'KEY-EIGHT merge (select-keys (meta #'input/KEY-EIGHT) [:doc :arglists :const]))
(def KEY-END input/KEY-END)
(alter-meta! #'KEY-END merge (select-keys (meta #'input/KEY-END) [:doc :arglists :const]))
(def KEY-ENTER input/KEY-ENTER)
(alter-meta! #'KEY-ENTER merge (select-keys (meta #'input/KEY-ENTER) [:doc :arglists :const]))
(def KEY-EQUAL input/KEY-EQUAL)
(alter-meta! #'KEY-EQUAL merge (select-keys (meta #'input/KEY-EQUAL) [:doc :arglists :const]))
(def KEY-ESCAPE input/KEY-ESCAPE)
(alter-meta! #'KEY-ESCAPE merge (select-keys (meta #'input/KEY-ESCAPE) [:doc :arglists :const]))
(def KEY-F input/KEY-F)
(alter-meta! #'KEY-F merge (select-keys (meta #'input/KEY-F) [:doc :arglists :const]))
(def KEY-F1 input/KEY-F1)
(alter-meta! #'KEY-F1 merge (select-keys (meta #'input/KEY-F1) [:doc :arglists :const]))
(def KEY-F10 input/KEY-F10)
(alter-meta! #'KEY-F10 merge (select-keys (meta #'input/KEY-F10) [:doc :arglists :const]))
(def KEY-F11 input/KEY-F11)
(alter-meta! #'KEY-F11 merge (select-keys (meta #'input/KEY-F11) [:doc :arglists :const]))
(def KEY-F12 input/KEY-F12)
(alter-meta! #'KEY-F12 merge (select-keys (meta #'input/KEY-F12) [:doc :arglists :const]))
(def KEY-F2 input/KEY-F2)
(alter-meta! #'KEY-F2 merge (select-keys (meta #'input/KEY-F2) [:doc :arglists :const]))
(def KEY-F3 input/KEY-F3)
(alter-meta! #'KEY-F3 merge (select-keys (meta #'input/KEY-F3) [:doc :arglists :const]))
(def KEY-F4 input/KEY-F4)
(alter-meta! #'KEY-F4 merge (select-keys (meta #'input/KEY-F4) [:doc :arglists :const]))
(def KEY-F5 input/KEY-F5)
(alter-meta! #'KEY-F5 merge (select-keys (meta #'input/KEY-F5) [:doc :arglists :const]))
(def KEY-F6 input/KEY-F6)
(alter-meta! #'KEY-F6 merge (select-keys (meta #'input/KEY-F6) [:doc :arglists :const]))
(def KEY-F7 input/KEY-F7)
(alter-meta! #'KEY-F7 merge (select-keys (meta #'input/KEY-F7) [:doc :arglists :const]))
(def KEY-F8 input/KEY-F8)
(alter-meta! #'KEY-F8 merge (select-keys (meta #'input/KEY-F8) [:doc :arglists :const]))
(def KEY-F9 input/KEY-F9)
(alter-meta! #'KEY-F9 merge (select-keys (meta #'input/KEY-F9) [:doc :arglists :const]))
(def KEY-FIVE input/KEY-FIVE)
(alter-meta! #'KEY-FIVE merge (select-keys (meta #'input/KEY-FIVE) [:doc :arglists :const]))
(def KEY-FOUR input/KEY-FOUR)
(alter-meta! #'KEY-FOUR merge (select-keys (meta #'input/KEY-FOUR) [:doc :arglists :const]))
(def KEY-G input/KEY-G)
(alter-meta! #'KEY-G merge (select-keys (meta #'input/KEY-G) [:doc :arglists :const]))
(def KEY-GRAVE input/KEY-GRAVE)
(alter-meta! #'KEY-GRAVE merge (select-keys (meta #'input/KEY-GRAVE) [:doc :arglists :const]))
(def KEY-H input/KEY-H)
(alter-meta! #'KEY-H merge (select-keys (meta #'input/KEY-H) [:doc :arglists :const]))
(def KEY-HOME input/KEY-HOME)
(alter-meta! #'KEY-HOME merge (select-keys (meta #'input/KEY-HOME) [:doc :arglists :const]))
(def KEY-I input/KEY-I)
(alter-meta! #'KEY-I merge (select-keys (meta #'input/KEY-I) [:doc :arglists :const]))
(def KEY-INSERT input/KEY-INSERT)
(alter-meta! #'KEY-INSERT merge (select-keys (meta #'input/KEY-INSERT) [:doc :arglists :const]))
(def KEY-J input/KEY-J)
(alter-meta! #'KEY-J merge (select-keys (meta #'input/KEY-J) [:doc :arglists :const]))
(def KEY-K input/KEY-K)
(alter-meta! #'KEY-K merge (select-keys (meta #'input/KEY-K) [:doc :arglists :const]))
(def KEY-L input/KEY-L)
(alter-meta! #'KEY-L merge (select-keys (meta #'input/KEY-L) [:doc :arglists :const]))
(def KEY-LEFT input/KEY-LEFT)
(alter-meta! #'KEY-LEFT merge (select-keys (meta #'input/KEY-LEFT) [:doc :arglists :const]))
(def KEY-LEFT-ALT input/KEY-LEFT-ALT)
(alter-meta! #'KEY-LEFT-ALT merge (select-keys (meta #'input/KEY-LEFT-ALT) [:doc :arglists :const]))
(def KEY-LEFT-BRACKET input/KEY-LEFT-BRACKET)
(alter-meta! #'KEY-LEFT-BRACKET merge (select-keys (meta #'input/KEY-LEFT-BRACKET) [:doc :arglists :const]))
(def KEY-LEFT-CONTROL input/KEY-LEFT-CONTROL)
(alter-meta! #'KEY-LEFT-CONTROL merge (select-keys (meta #'input/KEY-LEFT-CONTROL) [:doc :arglists :const]))
(def KEY-LEFT-SHIFT input/KEY-LEFT-SHIFT)
(alter-meta! #'KEY-LEFT-SHIFT merge (select-keys (meta #'input/KEY-LEFT-SHIFT) [:doc :arglists :const]))
(def KEY-LEFT-SUPER input/KEY-LEFT-SUPER)
(alter-meta! #'KEY-LEFT-SUPER merge (select-keys (meta #'input/KEY-LEFT-SUPER) [:doc :arglists :const]))
(def KEY-M input/KEY-M)
(alter-meta! #'KEY-M merge (select-keys (meta #'input/KEY-M) [:doc :arglists :const]))
(def KEY-MINUS input/KEY-MINUS)
(alter-meta! #'KEY-MINUS merge (select-keys (meta #'input/KEY-MINUS) [:doc :arglists :const]))
(def KEY-N input/KEY-N)
(alter-meta! #'KEY-N merge (select-keys (meta #'input/KEY-N) [:doc :arglists :const]))
(def KEY-NINE input/KEY-NINE)
(alter-meta! #'KEY-NINE merge (select-keys (meta #'input/KEY-NINE) [:doc :arglists :const]))
(def KEY-NULL input/KEY-NULL)
(alter-meta! #'KEY-NULL merge (select-keys (meta #'input/KEY-NULL) [:doc :arglists :const]))
(def KEY-O input/KEY-O)
(alter-meta! #'KEY-O merge (select-keys (meta #'input/KEY-O) [:doc :arglists :const]))
(def KEY-ONE input/KEY-ONE)
(alter-meta! #'KEY-ONE merge (select-keys (meta #'input/KEY-ONE) [:doc :arglists :const]))
(def KEY-P input/KEY-P)
(alter-meta! #'KEY-P merge (select-keys (meta #'input/KEY-P) [:doc :arglists :const]))
(def KEY-PAGE-DOWN input/KEY-PAGE-DOWN)
(alter-meta! #'KEY-PAGE-DOWN merge (select-keys (meta #'input/KEY-PAGE-DOWN) [:doc :arglists :const]))
(def KEY-PAGE-UP input/KEY-PAGE-UP)
(alter-meta! #'KEY-PAGE-UP merge (select-keys (meta #'input/KEY-PAGE-UP) [:doc :arglists :const]))
(def KEY-PAUSE input/KEY-PAUSE)
(alter-meta! #'KEY-PAUSE merge (select-keys (meta #'input/KEY-PAUSE) [:doc :arglists :const]))
(def KEY-PERIOD input/KEY-PERIOD)
(alter-meta! #'KEY-PERIOD merge (select-keys (meta #'input/KEY-PERIOD) [:doc :arglists :const]))
(def KEY-PRINT-SCREEN input/KEY-PRINT-SCREEN)
(alter-meta! #'KEY-PRINT-SCREEN merge (select-keys (meta #'input/KEY-PRINT-SCREEN) [:doc :arglists :const]))
(def KEY-Q input/KEY-Q)
(alter-meta! #'KEY-Q merge (select-keys (meta #'input/KEY-Q) [:doc :arglists :const]))
(def KEY-R input/KEY-R)
(alter-meta! #'KEY-R merge (select-keys (meta #'input/KEY-R) [:doc :arglists :const]))
(def KEY-RIGHT input/KEY-RIGHT)
(alter-meta! #'KEY-RIGHT merge (select-keys (meta #'input/KEY-RIGHT) [:doc :arglists :const]))
(def KEY-RIGHT-ALT input/KEY-RIGHT-ALT)
(alter-meta! #'KEY-RIGHT-ALT merge (select-keys (meta #'input/KEY-RIGHT-ALT) [:doc :arglists :const]))
(def KEY-RIGHT-BRACKET input/KEY-RIGHT-BRACKET)
(alter-meta! #'KEY-RIGHT-BRACKET merge (select-keys (meta #'input/KEY-RIGHT-BRACKET) [:doc :arglists :const]))
(def KEY-RIGHT-CONTROL input/KEY-RIGHT-CONTROL)
(alter-meta! #'KEY-RIGHT-CONTROL merge (select-keys (meta #'input/KEY-RIGHT-CONTROL) [:doc :arglists :const]))
(def KEY-RIGHT-SHIFT input/KEY-RIGHT-SHIFT)
(alter-meta! #'KEY-RIGHT-SHIFT merge (select-keys (meta #'input/KEY-RIGHT-SHIFT) [:doc :arglists :const]))
(def KEY-S input/KEY-S)
(alter-meta! #'KEY-S merge (select-keys (meta #'input/KEY-S) [:doc :arglists :const]))
(def KEY-SEMICOLON input/KEY-SEMICOLON)
(alter-meta! #'KEY-SEMICOLON merge (select-keys (meta #'input/KEY-SEMICOLON) [:doc :arglists :const]))
(def KEY-SEVEN input/KEY-SEVEN)
(alter-meta! #'KEY-SEVEN merge (select-keys (meta #'input/KEY-SEVEN) [:doc :arglists :const]))
(def KEY-SIX input/KEY-SIX)
(alter-meta! #'KEY-SIX merge (select-keys (meta #'input/KEY-SIX) [:doc :arglists :const]))
(def KEY-SLASH input/KEY-SLASH)
(alter-meta! #'KEY-SLASH merge (select-keys (meta #'input/KEY-SLASH) [:doc :arglists :const]))
(def KEY-SPACE input/KEY-SPACE)
(alter-meta! #'KEY-SPACE merge (select-keys (meta #'input/KEY-SPACE) [:doc :arglists :const]))
(def KEY-T input/KEY-T)
(alter-meta! #'KEY-T merge (select-keys (meta #'input/KEY-T) [:doc :arglists :const]))
(def KEY-TAB input/KEY-TAB)
(alter-meta! #'KEY-TAB merge (select-keys (meta #'input/KEY-TAB) [:doc :arglists :const]))
(def KEY-THREE input/KEY-THREE)
(alter-meta! #'KEY-THREE merge (select-keys (meta #'input/KEY-THREE) [:doc :arglists :const]))
(def KEY-TWO input/KEY-TWO)
(alter-meta! #'KEY-TWO merge (select-keys (meta #'input/KEY-TWO) [:doc :arglists :const]))
(def KEY-U input/KEY-U)
(alter-meta! #'KEY-U merge (select-keys (meta #'input/KEY-U) [:doc :arglists :const]))
(def KEY-UP input/KEY-UP)
(alter-meta! #'KEY-UP merge (select-keys (meta #'input/KEY-UP) [:doc :arglists :const]))
(def KEY-V input/KEY-V)
(alter-meta! #'KEY-V merge (select-keys (meta #'input/KEY-V) [:doc :arglists :const]))
(def KEY-W input/KEY-W)
(alter-meta! #'KEY-W merge (select-keys (meta #'input/KEY-W) [:doc :arglists :const]))
(def KEY-X input/KEY-X)
(alter-meta! #'KEY-X merge (select-keys (meta #'input/KEY-X) [:doc :arglists :const]))
(def KEY-Y input/KEY-Y)
(alter-meta! #'KEY-Y merge (select-keys (meta #'input/KEY-Y) [:doc :arglists :const]))
(def KEY-Z input/KEY-Z)
(alter-meta! #'KEY-Z merge (select-keys (meta #'input/KEY-Z) [:doc :arglists :const]))
(def KEY-ZERO input/KEY-ZERO)
(alter-meta! #'KEY-ZERO merge (select-keys (meta #'input/KEY-ZERO) [:doc :arglists :const]))
(def MOUSE-LEFT input/MOUSE-LEFT)
(alter-meta! #'MOUSE-LEFT merge (select-keys (meta #'input/MOUSE-LEFT) [:doc :arglists :const]))
(def MOUSE-MIDDLE input/MOUSE-MIDDLE)
(alter-meta! #'MOUSE-MIDDLE merge (select-keys (meta #'input/MOUSE-MIDDLE) [:doc :arglists :const]))
(def MOUSE-RIGHT input/MOUSE-RIGHT)
(alter-meta! #'MOUSE-RIGHT merge (select-keys (meta #'input/MOUSE-RIGHT) [:doc :arglists :const]))
(def PAD-A input/PAD-A)
(alter-meta! #'PAD-A merge (select-keys (meta #'input/PAD-A) [:doc :arglists :const]))
(def PAD-B input/PAD-B)
(alter-meta! #'PAD-B merge (select-keys (meta #'input/PAD-B) [:doc :arglists :const]))
(def PAD-DOWN input/PAD-DOWN)
(alter-meta! #'PAD-DOWN merge (select-keys (meta #'input/PAD-DOWN) [:doc :arglists :const]))
(def PAD-L1 input/PAD-L1)
(alter-meta! #'PAD-L1 merge (select-keys (meta #'input/PAD-L1) [:doc :arglists :const]))
(def PAD-L2 input/PAD-L2)
(alter-meta! #'PAD-L2 merge (select-keys (meta #'input/PAD-L2) [:doc :arglists :const]))
(def PAD-LEFT input/PAD-LEFT)
(alter-meta! #'PAD-LEFT merge (select-keys (meta #'input/PAD-LEFT) [:doc :arglists :const]))
(def PAD-MENU input/PAD-MENU)
(alter-meta! #'PAD-MENU merge (select-keys (meta #'input/PAD-MENU) [:doc :arglists :const]))
(def PAD-R1 input/PAD-R1)
(alter-meta! #'PAD-R1 merge (select-keys (meta #'input/PAD-R1) [:doc :arglists :const]))
(def PAD-R2 input/PAD-R2)
(alter-meta! #'PAD-R2 merge (select-keys (meta #'input/PAD-R2) [:doc :arglists :const]))
(def PAD-RIGHT input/PAD-RIGHT)
(alter-meta! #'PAD-RIGHT merge (select-keys (meta #'input/PAD-RIGHT) [:doc :arglists :const]))
(def PAD-SELECT input/PAD-SELECT)
(alter-meta! #'PAD-SELECT merge (select-keys (meta #'input/PAD-SELECT) [:doc :arglists :const]))
(def PAD-START input/PAD-START)
(alter-meta! #'PAD-START merge (select-keys (meta #'input/PAD-START) [:doc :arglists :const]))
(def PAD-UP input/PAD-UP)
(alter-meta! #'PAD-UP merge (select-keys (meta #'input/PAD-UP) [:doc :arglists :const]))
(def PAD-X input/PAD-X)
(alter-meta! #'PAD-X merge (select-keys (meta #'input/PAD-X) [:doc :arglists :const]))
(def PAD-Y input/PAD-Y)
(alter-meta! #'PAD-Y merge (select-keys (meta #'input/PAD-Y) [:doc :arglists :const]))
(def gamepad-available? input/gamepad-available?)
(alter-meta! #'gamepad-available? merge (select-keys (meta #'input/gamepad-available?) [:doc :arglists :const]))
(def gamepad-down? input/gamepad-down?)
(alter-meta! #'gamepad-down? merge (select-keys (meta #'input/gamepad-down?) [:doc :arglists :const]))
(def gamepad-pressed? input/gamepad-pressed?)
(alter-meta! #'gamepad-pressed? merge (select-keys (meta #'input/gamepad-pressed?) [:doc :arglists :const]))
(def gamepad-released? input/gamepad-released?)
(alter-meta! #'gamepad-released? merge (select-keys (meta #'input/gamepad-released?) [:doc :arglists :const]))
(def get-char-pressed input/get-char-pressed)
(alter-meta! #'get-char-pressed merge (select-keys (meta #'input/get-char-pressed) [:doc :arglists :const]))
(def get-gamepad-axis-count input/get-gamepad-axis-count)
(alter-meta! #'get-gamepad-axis-count merge (select-keys (meta #'input/get-gamepad-axis-count) [:doc :arglists :const]))
(def get-gamepad-axis-movement input/get-gamepad-axis-movement)
(alter-meta! #'get-gamepad-axis-movement merge (select-keys (meta #'input/get-gamepad-axis-movement) [:doc :arglists :const]))
(def get-gamepad-name input/get-gamepad-name)
(alter-meta! #'get-gamepad-name merge (select-keys (meta #'input/get-gamepad-name) [:doc :arglists :const]))
(def get-gesture-detected input/get-gesture-detected)
(alter-meta! #'get-gesture-detected merge (select-keys (meta #'input/get-gesture-detected) [:doc :arglists :const]))
(def get-key-pressed input/get-key-pressed)
(alter-meta! #'get-key-pressed merge (select-keys (meta #'input/get-key-pressed) [:doc :arglists :const]))
(def get-mouse-wheel input/get-mouse-wheel)
(alter-meta! #'get-mouse-wheel merge (select-keys (meta #'input/get-mouse-wheel) [:doc :arglists :const]))
(def get-mouse-x input/get-mouse-x)
(alter-meta! #'get-mouse-x merge (select-keys (meta #'input/get-mouse-x) [:doc :arglists :const]))
(def get-mouse-y input/get-mouse-y)
(alter-meta! #'get-mouse-y merge (select-keys (meta #'input/get-mouse-y) [:doc :arglists :const]))
(def get-random-value input/get-random-value)
(alter-meta! #'get-random-value merge (select-keys (meta #'input/get-random-value) [:doc :arglists :const]))
(def get-touch-point-count input/get-touch-point-count)
(alter-meta! #'get-touch-point-count merge (select-keys (meta #'input/get-touch-point-count) [:doc :arglists :const]))
(def get-touch-point-id input/get-touch-point-id)
(alter-meta! #'get-touch-point-id merge (select-keys (meta #'input/get-touch-point-id) [:doc :arglists :const]))
(def get-touch-x input/get-touch-x)
(alter-meta! #'get-touch-x merge (select-keys (meta #'input/get-touch-x) [:doc :arglists :const]))
(def get-touch-y input/get-touch-y)
(alter-meta! #'get-touch-y merge (select-keys (meta #'input/get-touch-y) [:doc :arglists :const]))
(def hide-cursor input/hide-cursor)
(alter-meta! #'hide-cursor merge (select-keys (meta #'input/hide-cursor) [:doc :arglists :const]))
(def key-down? input/key-down?)
(alter-meta! #'key-down? merge (select-keys (meta #'input/key-down?) [:doc :arglists :const]))
(def key-pressed? input/key-pressed?)
(alter-meta! #'key-pressed? merge (select-keys (meta #'input/key-pressed?) [:doc :arglists :const]))
(def key-released? input/key-released?)
(alter-meta! #'key-released? merge (select-keys (meta #'input/key-released?) [:doc :arglists :const]))
(def mouse-down? input/mouse-down?)
(alter-meta! #'mouse-down? merge (select-keys (meta #'input/mouse-down?) [:doc :arglists :const]))
(def mouse-pressed? input/mouse-pressed?)
(alter-meta! #'mouse-pressed? merge (select-keys (meta #'input/mouse-pressed?) [:doc :arglists :const]))
(def mouse-released? input/mouse-released?)
(alter-meta! #'mouse-released? merge (select-keys (meta #'input/mouse-released?) [:doc :arglists :const]))
(def set-gestures-enabled input/set-gestures-enabled)
(alter-meta! #'set-gestures-enabled merge (select-keys (meta #'input/set-gestures-enabled) [:doc :arglists :const]))
(def set-mouse-cursor input/set-mouse-cursor)
(alter-meta! #'set-mouse-cursor merge (select-keys (meta #'input/set-mouse-cursor) [:doc :arglists :const]))
(def set-mouse-position input/set-mouse-position)
(alter-meta! #'set-mouse-position merge (select-keys (meta #'input/set-mouse-position) [:doc :arglists :const]))
(def show-cursor input/show-cursor)
(alter-meta! #'show-cursor merge (select-keys (meta #'input/show-cursor) [:doc :arglists :const]))

;; --- kwargs (15) --------------------------------------------------------
(def circle! kwargs/circle!)
(alter-meta! #'circle! merge (select-keys (meta #'kwargs/circle!) [:doc :arglists :const]))
(def circle-lines! kwargs/circle-lines!)
(alter-meta! #'circle-lines! merge (select-keys (meta #'kwargs/circle-lines!) [:doc :arglists :const]))
(def ellipse! kwargs/ellipse!)
(alter-meta! #'ellipse! merge (select-keys (meta #'kwargs/ellipse!) [:doc :arglists :const]))
(def fps! kwargs/fps!)
(alter-meta! #'fps! merge (select-keys (meta #'kwargs/fps!) [:doc :arglists :const]))
(def line! kwargs/line!)
(alter-meta! #'line! merge (select-keys (meta #'kwargs/line!) [:doc :arglists :const]))
(def line-ex! kwargs/line-ex!)
(alter-meta! #'line-ex! merge (select-keys (meta #'kwargs/line-ex!) [:doc :arglists :const]))
(def pixel! kwargs/pixel!)
(alter-meta! #'pixel! merge (select-keys (meta #'kwargs/pixel!) [:doc :arglists :const]))
(def rect! kwargs/rect!)
(alter-meta! #'rect! merge (select-keys (meta #'kwargs/rect!) [:doc :arglists :const]))
(def rect-gradient! kwargs/rect-gradient!)
(alter-meta! #'rect-gradient! merge (select-keys (meta #'kwargs/rect-gradient!) [:doc :arglists :const]))
(def rect-lines! kwargs/rect-lines!)
(alter-meta! #'rect-lines! merge (select-keys (meta #'kwargs/rect-lines!) [:doc :arglists :const]))
(def ring! kwargs/ring!)
(alter-meta! #'ring! merge (select-keys (meta #'kwargs/ring!) [:doc :arglists :const]))
(def sector! kwargs/sector!)
(alter-meta! #'sector! merge (select-keys (meta #'kwargs/sector!) [:doc :arglists :const]))
(def text! kwargs/text!)
(alter-meta! #'text! merge (select-keys (meta #'kwargs/text!) [:doc :arglists :const]))
(def text-width kwargs/text-width)
(alter-meta! #'text-width merge (select-keys (meta #'kwargs/text-width) [:doc :arglists :const]))
(def window! kwargs/window!)
(alter-meta! #'window! merge (select-keys (meta #'kwargs/window!) [:doc :arglists :const]))

;; --- log (10) -----------------------------------------------------------
(def LOG-DEBUG log/LOG-DEBUG)
(alter-meta! #'LOG-DEBUG merge (select-keys (meta #'log/LOG-DEBUG) [:doc :arglists :const]))
(def LOG-ERROR log/LOG-ERROR)
(alter-meta! #'LOG-ERROR merge (select-keys (meta #'log/LOG-ERROR) [:doc :arglists :const]))
(def LOG-FATAL log/LOG-FATAL)
(alter-meta! #'LOG-FATAL merge (select-keys (meta #'log/LOG-FATAL) [:doc :arglists :const]))
(def LOG-INFO log/LOG-INFO)
(alter-meta! #'LOG-INFO merge (select-keys (meta #'log/LOG-INFO) [:doc :arglists :const]))
(def LOG-TRACE log/LOG-TRACE)
(alter-meta! #'LOG-TRACE merge (select-keys (meta #'log/LOG-TRACE) [:doc :arglists :const]))
(def LOG-WARNING log/LOG-WARNING)
(alter-meta! #'LOG-WARNING merge (select-keys (meta #'log/LOG-WARNING) [:doc :arglists :const]))
(def TRACE-LOG-BUFFER log/TRACE-LOG-BUFFER)
(alter-meta! #'TRACE-LOG-BUFFER merge (select-keys (meta #'log/TRACE-LOG-BUFFER) [:doc :arglists :const]))
(def free-callable! log/free-callable!)
(alter-meta! #'free-callable! merge (select-keys (meta #'log/free-callable!) [:doc :arglists :const]))
(def on-trace-log! log/on-trace-log!)
(alter-meta! #'on-trace-log! merge (select-keys (meta #'log/on-trace-log!) [:doc :arglists :const]))
(def set-trace-log-callback log/set-trace-log-callback)
(alter-meta! #'set-trace-log-callback merge (select-keys (meta #'log/set-trace-log-callback) [:doc :arglists :const]))

;; --- models (18) --------------------------------------------------------
(def cube! models/cube!)
(alter-meta! #'cube! merge (select-keys (meta #'models/cube!) [:doc :arglists :const]))
(def draw-capsule! models/draw-capsule!)
(alter-meta! #'draw-capsule! merge (select-keys (meta #'models/draw-capsule!) [:doc :arglists :const]))
(def draw-capsule-wires! models/draw-capsule-wires!)
(alter-meta! #'draw-capsule-wires! merge (select-keys (meta #'models/draw-capsule-wires!) [:doc :arglists :const]))
(def draw-cube! models/draw-cube!)
(alter-meta! #'draw-cube! merge (select-keys (meta #'models/draw-cube!) [:doc :arglists :const]))
(def draw-cube-wires! models/draw-cube-wires!)
(alter-meta! #'draw-cube-wires! merge (select-keys (meta #'models/draw-cube-wires!) [:doc :arglists :const]))
(def draw-cylinder! models/draw-cylinder!)
(alter-meta! #'draw-cylinder! merge (select-keys (meta #'models/draw-cylinder!) [:doc :arglists :const]))
(def draw-cylinder-wires! models/draw-cylinder-wires!)
(alter-meta! #'draw-cylinder-wires! merge (select-keys (meta #'models/draw-cylinder-wires!) [:doc :arglists :const]))
(def draw-grid models/draw-grid)
(alter-meta! #'draw-grid merge (select-keys (meta #'models/draw-grid) [:doc :arglists :const]))
(def draw-plane! models/draw-plane!)
(alter-meta! #'draw-plane! merge (select-keys (meta #'models/draw-plane!) [:doc :arglists :const]))
(def draw-sphere! models/draw-sphere!)
(alter-meta! #'draw-sphere! merge (select-keys (meta #'models/draw-sphere!) [:doc :arglists :const]))
(def draw-sphere-wires! models/draw-sphere-wires!)
(alter-meta! #'draw-sphere-wires! merge (select-keys (meta #'models/draw-sphere-wires!) [:doc :arglists :const]))
(def rl-pop-matrix models/rl-pop-matrix)
(alter-meta! #'rl-pop-matrix merge (select-keys (meta #'models/rl-pop-matrix) [:doc :arglists :const]))
(def rl-push-matrix models/rl-push-matrix)
(alter-meta! #'rl-push-matrix merge (select-keys (meta #'models/rl-push-matrix) [:doc :arglists :const]))
(def rl-rotatef models/rl-rotatef)
(alter-meta! #'rl-rotatef merge (select-keys (meta #'models/rl-rotatef) [:doc :arglists :const]))
(def rl-scalef models/rl-scalef)
(alter-meta! #'rl-scalef merge (select-keys (meta #'models/rl-scalef) [:doc :arglists :const]))
(def rl-translatef models/rl-translatef)
(alter-meta! #'rl-translatef merge (select-keys (meta #'models/rl-translatef) [:doc :arglists :const]))
(def rl-vertex-3f models/rl-vertex-3f)
(alter-meta! #'rl-vertex-3f merge (select-keys (meta #'models/rl-vertex-3f) [:doc :arglists :const]))
(def sphere! models/sphere!)
(alter-meta! #'sphere! merge (select-keys (meta #'models/sphere!) [:doc :arglists :const]))

;; --- native (7) --------------------------------------------------------
(def PIXELFORMAT-R8G8B8 native/PIXELFORMAT-R8G8B8)
(alter-meta! #'PIXELFORMAT-R8G8B8 merge (select-keys (meta #'native/PIXELFORMAT-R8G8B8) [:doc :arglists :const]))
(def PIXELFORMAT-R8G8B8A8 native/PIXELFORMAT-R8G8B8A8)
(alter-meta! #'PIXELFORMAT-R8G8B8A8 merge (select-keys (meta #'native/PIXELFORMAT-R8G8B8A8) [:doc :arglists :const]))
(def staged native/staged)
(alter-meta! #'staged merge (select-keys (meta #'native/staged) [:doc :arglists :const]))
(def texture2d-layout native/texture2d-layout)
(alter-meta! #'texture2d-layout merge (select-keys (meta #'native/texture2d-layout) [:doc :arglists :const]))
(def vec2->ptr! native/vec2->ptr!)
(alter-meta! #'vec2->ptr! merge (select-keys (meta #'native/vec2->ptr!) [:doc :arglists :const]))
(def vector2-layout native/vector2-layout)
(alter-meta! #'vector2-layout merge (select-keys (meta #'native/vector2-layout) [:doc :arglists :const]))
(def vector3-layout native/vector3-layout)
(alter-meta! #'vector3-layout merge (select-keys (meta #'native/vector3-layout) [:doc :arglists :const]))

;; --- rays (4) ----------------------------------------------------------
(def cursor-hidden? rays/cursor-hidden?)
(alter-meta! #'cursor-hidden? merge (select-keys (meta #'rays/cursor-hidden?) [:doc :arglists :const]))
(def draw-ray! rays/draw-ray!)
(alter-meta! #'draw-ray! merge (select-keys (meta #'rays/draw-ray!) [:doc :arglists :const]))
(def ray-collision-box rays/ray-collision-box)
(alter-meta! #'ray-collision-box merge (select-keys (meta #'rays/ray-collision-box) [:doc :arglists :const]))
(def screen-to-world-ray rays/screen-to-world-ray)
(alter-meta! #'screen-to-world-ray merge (select-keys (meta #'rays/screen-to-world-ray) [:doc :arglists :const]))

;; --- rlgl (10) ----------------------------------------------------------
(def RL-LINES rlgl/RL-LINES)
(alter-meta! #'RL-LINES merge (select-keys (meta #'rlgl/RL-LINES) [:doc :arglists :const]))
(def RL-TRIANGLES rlgl/RL-TRIANGLES)
(alter-meta! #'RL-TRIANGLES merge (select-keys (meta #'rlgl/RL-TRIANGLES) [:doc :arglists :const]))
(def flush-batch rlgl/flush-batch)
(alter-meta! #'flush-batch merge (select-keys (meta #'rlgl/flush-batch) [:doc :arglists :const]))
(def rl-begin rlgl/rl-begin)
(alter-meta! #'rl-begin merge (select-keys (meta #'rlgl/rl-begin) [:doc :arglists :const]))
(def rl-color! rlgl/rl-color!)
(alter-meta! #'rl-color! merge (select-keys (meta #'rlgl/rl-color!) [:doc :arglists :const]))
(def rl-color-4ub rlgl/rl-color-4ub)
(alter-meta! #'rl-color-4ub merge (select-keys (meta #'rlgl/rl-color-4ub) [:doc :arglists :const]))
(def rl-disable-backface-culling rlgl/rl-disable-backface-culling)
(alter-meta! #'rl-disable-backface-culling merge (select-keys (meta #'rlgl/rl-disable-backface-culling) [:doc :arglists :const]))
(def rl-enable-backface-culling rlgl/rl-enable-backface-culling)
(alter-meta! #'rl-enable-backface-culling merge (select-keys (meta #'rlgl/rl-enable-backface-culling) [:doc :arglists :const]))
(def rl-end rlgl/rl-end)
(alter-meta! #'rl-end merge (select-keys (meta #'rlgl/rl-end) [:doc :arglists :const]))
(def rl-vertex-2f rlgl/rl-vertex-2f)
(alter-meta! #'rl-vertex-2f merge (select-keys (meta #'rlgl/rl-vertex-2f) [:doc :arglists :const]))

;; --- shaders (22) -------------------------------------------------------
(def UNIFORM-FLOAT shaders/UNIFORM-FLOAT)
(alter-meta! #'UNIFORM-FLOAT merge (select-keys (meta #'shaders/UNIFORM-FLOAT) [:doc :arglists :const]))
(def UNIFORM-INT shaders/UNIFORM-INT)
(alter-meta! #'UNIFORM-INT merge (select-keys (meta #'shaders/UNIFORM-INT) [:doc :arglists :const]))
(def UNIFORM-IVEC2 shaders/UNIFORM-IVEC2)
(alter-meta! #'UNIFORM-IVEC2 merge (select-keys (meta #'shaders/UNIFORM-IVEC2) [:doc :arglists :const]))
(def UNIFORM-IVEC3 shaders/UNIFORM-IVEC3)
(alter-meta! #'UNIFORM-IVEC3 merge (select-keys (meta #'shaders/UNIFORM-IVEC3) [:doc :arglists :const]))
(def UNIFORM-IVEC4 shaders/UNIFORM-IVEC4)
(alter-meta! #'UNIFORM-IVEC4 merge (select-keys (meta #'shaders/UNIFORM-IVEC4) [:doc :arglists :const]))
(def UNIFORM-SAMPLER2D shaders/UNIFORM-SAMPLER2D)
(alter-meta! #'UNIFORM-SAMPLER2D merge (select-keys (meta #'shaders/UNIFORM-SAMPLER2D) [:doc :arglists :const]))
(def UNIFORM-VEC2 shaders/UNIFORM-VEC2)
(alter-meta! #'UNIFORM-VEC2 merge (select-keys (meta #'shaders/UNIFORM-VEC2) [:doc :arglists :const]))
(def UNIFORM-VEC3 shaders/UNIFORM-VEC3)
(alter-meta! #'UNIFORM-VEC3 merge (select-keys (meta #'shaders/UNIFORM-VEC3) [:doc :arglists :const]))
(def UNIFORM-VEC4 shaders/UNIFORM-VEC4)
(alter-meta! #'UNIFORM-VEC4 merge (select-keys (meta #'shaders/UNIFORM-VEC4) [:doc :arglists :const]))
(def end-shader-mode shaders/end-shader-mode)
(alter-meta! #'end-shader-mode merge (select-keys (meta #'shaders/end-shader-mode) [:doc :arglists :const]))
(def set-uniform-float! shaders/set-uniform-float!)
(alter-meta! #'set-uniform-float! merge (select-keys (meta #'shaders/set-uniform-float!) [:doc :arglists :const]))
(def set-uniform-int! shaders/set-uniform-int!)
(alter-meta! #'set-uniform-int! merge (select-keys (meta #'shaders/set-uniform-int!) [:doc :arglists :const]))
(def set-uniform-ivec3-array! shaders/set-uniform-ivec3-array!)
(alter-meta! #'set-uniform-ivec3-array! merge (select-keys (meta #'shaders/set-uniform-ivec3-array!) [:doc :arglists :const]))
(def set-uniform-texture! shaders/set-uniform-texture!)
(alter-meta! #'set-uniform-texture! merge (select-keys (meta #'shaders/set-uniform-texture!) [:doc :arglists :const]))
(def set-uniform-vec2! shaders/set-uniform-vec2!)
(alter-meta! #'set-uniform-vec2! merge (select-keys (meta #'shaders/set-uniform-vec2!) [:doc :arglists :const]))
(def set-uniform-vec3! shaders/set-uniform-vec3!)
(alter-meta! #'set-uniform-vec3! merge (select-keys (meta #'shaders/set-uniform-vec3!) [:doc :arglists :const]))
(def set-uniform-vec4! shaders/set-uniform-vec4!)
(alter-meta! #'set-uniform-vec4! merge (select-keys (meta #'shaders/set-uniform-vec4!) [:doc :arglists :const]))
(def shader shaders/shader)
(alter-meta! #'shader merge (select-keys (meta #'shaders/shader) [:doc :arglists :const]))
(def shader-layout shaders/shader-layout)
(alter-meta! #'shader-layout merge (select-keys (meta #'shaders/shader-layout) [:doc :arglists :const]))
(def uniform-loc shaders/uniform-loc)
(alter-meta! #'uniform-loc merge (select-keys (meta #'shaders/uniform-loc) [:doc :arglists :const]))
(def unload-shader! shaders/unload-shader!)
(alter-meta! #'unload-shader! merge (select-keys (meta #'shaders/unload-shader!) [:doc :arglists :const]))
(def with-shader shaders/with-shader)
(alter-meta! #'with-shader merge (select-keys (meta #'shaders/with-shader) [:doc :arglists :const]))

;; --- shapes (24) --------------------------------------------------------
(def BLEND-ADD-COLORS shapes/BLEND-ADD-COLORS)
(alter-meta! #'BLEND-ADD-COLORS merge (select-keys (meta #'shapes/BLEND-ADD-COLORS) [:doc :arglists :const]))
(def BLEND-ADDITIVE shapes/BLEND-ADDITIVE)
(alter-meta! #'BLEND-ADDITIVE merge (select-keys (meta #'shapes/BLEND-ADDITIVE) [:doc :arglists :const]))
(def BLEND-ALPHA shapes/BLEND-ALPHA)
(alter-meta! #'BLEND-ALPHA merge (select-keys (meta #'shapes/BLEND-ALPHA) [:doc :arglists :const]))
(def BLEND-CUSTOM shapes/BLEND-CUSTOM)
(alter-meta! #'BLEND-CUSTOM merge (select-keys (meta #'shapes/BLEND-CUSTOM) [:doc :arglists :const]))
(def BLEND-MULTIPLIED shapes/BLEND-MULTIPLIED)
(alter-meta! #'BLEND-MULTIPLIED merge (select-keys (meta #'shapes/BLEND-MULTIPLIED) [:doc :arglists :const]))
(def BLEND-SUBTRACT-COLORS shapes/BLEND-SUBTRACT-COLORS)
(alter-meta! #'BLEND-SUBTRACT-COLORS merge (select-keys (meta #'shapes/BLEND-SUBTRACT-COLORS) [:doc :arglists :const]))
(def GL-MAX shapes/GL-MAX)
(alter-meta! #'GL-MAX merge (select-keys (meta #'shapes/GL-MAX) [:doc :arglists :const]))
(def GL-MIN shapes/GL-MIN)
(alter-meta! #'GL-MIN merge (select-keys (meta #'shapes/GL-MIN) [:doc :arglists :const]))
(def GL-SRC-ALPHA shapes/GL-SRC-ALPHA)
(alter-meta! #'GL-SRC-ALPHA merge (select-keys (meta #'shapes/GL-SRC-ALPHA) [:doc :arglists :const]))
(def begin-blend-mode shapes/begin-blend-mode)
(alter-meta! #'begin-blend-mode merge (select-keys (meta #'shapes/begin-blend-mode) [:doc :arglists :const]))
(def circle-gradient! shapes/circle-gradient!)
(alter-meta! #'circle-gradient! merge (select-keys (meta #'shapes/circle-gradient!) [:doc :arglists :const]))
(def draw-circle shapes/draw-circle)
(alter-meta! #'draw-circle merge (select-keys (meta #'shapes/draw-circle) [:doc :arglists :const]))
(def draw-circle-lines shapes/draw-circle-lines)
(alter-meta! #'draw-circle-lines merge (select-keys (meta #'shapes/draw-circle-lines) [:doc :arglists :const]))
(def draw-ellipse shapes/draw-ellipse)
(alter-meta! #'draw-ellipse merge (select-keys (meta #'shapes/draw-ellipse) [:doc :arglists :const]))
(def draw-line shapes/draw-line)
(alter-meta! #'draw-line merge (select-keys (meta #'shapes/draw-line) [:doc :arglists :const]))
(def draw-pixel shapes/draw-pixel)
(alter-meta! #'draw-pixel merge (select-keys (meta #'shapes/draw-pixel) [:doc :arglists :const]))
(def draw-rectangle shapes/draw-rectangle)
(alter-meta! #'draw-rectangle merge (select-keys (meta #'shapes/draw-rectangle) [:doc :arglists :const]))
(def draw-rectangle-grad-h shapes/draw-rectangle-grad-h)
(alter-meta! #'draw-rectangle-grad-h merge (select-keys (meta #'shapes/draw-rectangle-grad-h) [:doc :arglists :const]))
(def draw-rectangle-grad-v shapes/draw-rectangle-grad-v)
(alter-meta! #'draw-rectangle-grad-v merge (select-keys (meta #'shapes/draw-rectangle-grad-v) [:doc :arglists :const]))
(def draw-rectangle-lines shapes/draw-rectangle-lines)
(alter-meta! #'draw-rectangle-lines merge (select-keys (meta #'shapes/draw-rectangle-lines) [:doc :arglists :const]))
(def end-blend-mode shapes/end-blend-mode)
(alter-meta! #'end-blend-mode merge (select-keys (meta #'shapes/end-blend-mode) [:doc :arglists :const]))
(def rect-gradient-h! shapes/rect-gradient-h!)
(alter-meta! #'rect-gradient-h! merge (select-keys (meta #'shapes/rect-gradient-h!) [:doc :arglists :const]))
(def rect-pro! shapes/rect-pro!)
(alter-meta! #'rect-pro! merge (select-keys (meta #'shapes/rect-pro!) [:doc :arglists :const]))
(def set-blend-factors shapes/set-blend-factors)
(alter-meta! #'set-blend-factors merge (select-keys (meta #'shapes/set-blend-factors) [:doc :arglists :const]))

;; --- splines (4) -------------------------------------------------------
(def spline-segment-basis! splines/spline-segment-basis!)
(alter-meta! #'spline-segment-basis! merge (select-keys (meta #'splines/spline-segment-basis!) [:doc :arglists :const]))
(def spline-segment-bezier-cubic! splines/spline-segment-bezier-cubic!)
(alter-meta! #'spline-segment-bezier-cubic! merge (select-keys (meta #'splines/spline-segment-bezier-cubic!) [:doc :arglists :const]))
(def spline-segment-catmull-rom! splines/spline-segment-catmull-rom!)
(alter-meta! #'spline-segment-catmull-rom! merge (select-keys (meta #'splines/spline-segment-catmull-rom!) [:doc :arglists :const]))
(def spline-segment-linear! splines/spline-segment-linear!)
(alter-meta! #'spline-segment-linear! merge (select-keys (meta #'splines/spline-segment-linear!) [:doc :arglists :const]))

;; --- text (3) ----------------------------------------------------------
(def draw-fps text/draw-fps)
(alter-meta! #'draw-fps merge (select-keys (meta #'text/draw-fps) [:doc :arglists :const]))
(def draw-text text/draw-text)
(alter-meta! #'draw-text merge (select-keys (meta #'text/draw-text) [:doc :arglists :const]))
(def measure-text text/measure-text)
(alter-meta! #'measure-text merge (select-keys (meta #'text/measure-text) [:doc :arglists :const]))

;; --- textures (48) ------------------------------------------------------
(def RL-ATTACHMENT-COLOR-CHANNEL0 textures/RL-ATTACHMENT-COLOR-CHANNEL0)
(alter-meta! #'RL-ATTACHMENT-COLOR-CHANNEL0 merge (select-keys (meta #'textures/RL-ATTACHMENT-COLOR-CHANNEL0) [:doc :arglists :const]))
(def RL-ATTACHMENT-DEPTH textures/RL-ATTACHMENT-DEPTH)
(alter-meta! #'RL-ATTACHMENT-DEPTH merge (select-keys (meta #'textures/RL-ATTACHMENT-DEPTH) [:doc :arglists :const]))
(def RL-ATTACHMENT-RENDERBUFFER textures/RL-ATTACHMENT-RENDERBUFFER)
(alter-meta! #'RL-ATTACHMENT-RENDERBUFFER merge (select-keys (meta #'textures/RL-ATTACHMENT-RENDERBUFFER) [:doc :arglists :const]))
(def RL-ATTACHMENT-TEXTURE2D textures/RL-ATTACHMENT-TEXTURE2D)
(alter-meta! #'RL-ATTACHMENT-TEXTURE2D merge (select-keys (meta #'textures/RL-ATTACHMENT-TEXTURE2D) [:doc :arglists :const]))
(def RL-MODELVIEW textures/RL-MODELVIEW)
(alter-meta! #'RL-MODELVIEW merge (select-keys (meta #'textures/RL-MODELVIEW) [:doc :arglists :const]))
(def RL-PROJECTION textures/RL-PROJECTION)
(alter-meta! #'RL-PROJECTION merge (select-keys (meta #'textures/RL-PROJECTION) [:doc :arglists :const]))
(def RL-QUADS textures/RL-QUADS)
(alter-meta! #'RL-QUADS merge (select-keys (meta #'textures/RL-QUADS) [:doc :arglists :const]))
(def RL-TEXTURE-FILTER-LINEAR textures/RL-TEXTURE-FILTER-LINEAR)
(alter-meta! #'RL-TEXTURE-FILTER-LINEAR merge (select-keys (meta #'textures/RL-TEXTURE-FILTER-LINEAR) [:doc :arglists :const]))
(def RL-TEXTURE-FILTER-NEAREST textures/RL-TEXTURE-FILTER-NEAREST)
(alter-meta! #'RL-TEXTURE-FILTER-NEAREST merge (select-keys (meta #'textures/RL-TEXTURE-FILTER-NEAREST) [:doc :arglists :const]))
(def RL-TEXTURE-MAG-FILTER textures/RL-TEXTURE-MAG-FILTER)
(alter-meta! #'RL-TEXTURE-MAG-FILTER merge (select-keys (meta #'textures/RL-TEXTURE-MAG-FILTER) [:doc :arglists :const]))
(def RL-TEXTURE-MIN-FILTER textures/RL-TEXTURE-MIN-FILTER)
(alter-meta! #'RL-TEXTURE-MIN-FILTER merge (select-keys (meta #'textures/RL-TEXTURE-MIN-FILTER) [:doc :arglists :const]))
(def RL-TEXTURE-WRAP-CLAMP textures/RL-TEXTURE-WRAP-CLAMP)
(alter-meta! #'RL-TEXTURE-WRAP-CLAMP merge (select-keys (meta #'textures/RL-TEXTURE-WRAP-CLAMP) [:doc :arglists :const]))
(def RL-TEXTURE-WRAP-REPEAT textures/RL-TEXTURE-WRAP-REPEAT)
(alter-meta! #'RL-TEXTURE-WRAP-REPEAT merge (select-keys (meta #'textures/RL-TEXTURE-WRAP-REPEAT) [:doc :arglists :const]))
(def RL-TEXTURE-WRAP-S textures/RL-TEXTURE-WRAP-S)
(alter-meta! #'RL-TEXTURE-WRAP-S merge (select-keys (meta #'textures/RL-TEXTURE-WRAP-S) [:doc :arglists :const]))
(def RL-TEXTURE-WRAP-T textures/RL-TEXTURE-WRAP-T)
(alter-meta! #'RL-TEXTURE-WRAP-T merge (select-keys (meta #'textures/RL-TEXTURE-WRAP-T) [:doc :arglists :const]))
(def get-render-height textures/get-render-height)
(alter-meta! #'get-render-height merge (select-keys (meta #'textures/get-render-height) [:doc :arglists :const]))
(def get-render-width textures/get-render-width)
(alter-meta! #'get-render-width merge (select-keys (meta #'textures/get-render-width) [:doc :arglists :const]))
(def render-texture textures/render-texture)
(alter-meta! #'render-texture merge (select-keys (meta #'textures/render-texture) [:doc :arglists :const]))
(def rl-disable-framebuffer textures/rl-disable-framebuffer)
(alter-meta! #'rl-disable-framebuffer merge (select-keys (meta #'textures/rl-disable-framebuffer) [:doc :arglists :const]))
(def rl-enable-framebuffer textures/rl-enable-framebuffer)
(alter-meta! #'rl-enable-framebuffer merge (select-keys (meta #'textures/rl-enable-framebuffer) [:doc :arglists :const]))
(def rl-framebuffer-attach textures/rl-framebuffer-attach)
(alter-meta! #'rl-framebuffer-attach merge (select-keys (meta #'textures/rl-framebuffer-attach) [:doc :arglists :const]))
(def rl-get-framebuffer-height textures/rl-get-framebuffer-height)
(alter-meta! #'rl-get-framebuffer-height merge (select-keys (meta #'textures/rl-get-framebuffer-height) [:doc :arglists :const]))
(def rl-get-framebuffer-width textures/rl-get-framebuffer-width)
(alter-meta! #'rl-get-framebuffer-width merge (select-keys (meta #'textures/rl-get-framebuffer-width) [:doc :arglists :const]))
(def rl-load-framebuffer textures/rl-load-framebuffer)
(alter-meta! #'rl-load-framebuffer merge (select-keys (meta #'textures/rl-load-framebuffer) [:doc :arglists :const]))
(def rl-load-identity textures/rl-load-identity)
(alter-meta! #'rl-load-identity merge (select-keys (meta #'textures/rl-load-identity) [:doc :arglists :const]))
(def rl-load-texture textures/rl-load-texture)
(alter-meta! #'rl-load-texture merge (select-keys (meta #'textures/rl-load-texture) [:doc :arglists :const]))
(def rl-load-texture-depth textures/rl-load-texture-depth)
(alter-meta! #'rl-load-texture-depth merge (select-keys (meta #'textures/rl-load-texture-depth) [:doc :arglists :const]))
(def rl-matrix-mode textures/rl-matrix-mode)
(alter-meta! #'rl-matrix-mode merge (select-keys (meta #'textures/rl-matrix-mode) [:doc :arglists :const]))
(def rl-mult-matrix-f textures/rl-mult-matrix-f)
(alter-meta! #'rl-mult-matrix-f merge (select-keys (meta #'textures/rl-mult-matrix-f) [:doc :arglists :const]))
(def rl-normal-3f textures/rl-normal-3f)
(alter-meta! #'rl-normal-3f merge (select-keys (meta #'textures/rl-normal-3f) [:doc :arglists :const]))
(def rl-ortho textures/rl-ortho)
(alter-meta! #'rl-ortho merge (select-keys (meta #'textures/rl-ortho) [:doc :arglists :const]))
(def rl-set-framebuffer-height textures/rl-set-framebuffer-height)
(alter-meta! #'rl-set-framebuffer-height merge (select-keys (meta #'textures/rl-set-framebuffer-height) [:doc :arglists :const]))
(def rl-set-framebuffer-width textures/rl-set-framebuffer-width)
(alter-meta! #'rl-set-framebuffer-width merge (select-keys (meta #'textures/rl-set-framebuffer-width) [:doc :arglists :const]))
(def rl-set-texture textures/rl-set-texture)
(alter-meta! #'rl-set-texture merge (select-keys (meta #'textures/rl-set-texture) [:doc :arglists :const]))
(def rl-tex-coord-2f textures/rl-tex-coord-2f)
(alter-meta! #'rl-tex-coord-2f merge (select-keys (meta #'textures/rl-tex-coord-2f) [:doc :arglists :const]))
(def rl-texture-parameters textures/rl-texture-parameters)
(alter-meta! #'rl-texture-parameters merge (select-keys (meta #'textures/rl-texture-parameters) [:doc :arglists :const]))
(def rl-unload-framebuffer textures/rl-unload-framebuffer)
(alter-meta! #'rl-unload-framebuffer merge (select-keys (meta #'textures/rl-unload-framebuffer) [:doc :arglists :const]))
(def rl-unload-texture textures/rl-unload-texture)
(alter-meta! #'rl-unload-texture merge (select-keys (meta #'textures/rl-unload-texture) [:doc :arglists :const]))
(def rl-update-texture textures/rl-update-texture)
(alter-meta! #'rl-update-texture merge (select-keys (meta #'textures/rl-update-texture) [:doc :arglists :const]))
(def rl-viewport textures/rl-viewport)
(alter-meta! #'rl-viewport merge (select-keys (meta #'textures/rl-viewport) [:doc :arglists :const]))
(def texture! textures/texture!)
(alter-meta! #'texture! merge (select-keys (meta #'textures/texture!) [:doc :arglists :const]))
(def texture-filter! textures/texture-filter!)
(alter-meta! #'texture-filter! merge (select-keys (meta #'textures/texture-filter!) [:doc :arglists :const]))
(def texture-from-fn textures/texture-from-fn)
(alter-meta! #'texture-from-fn merge (select-keys (meta #'textures/texture-from-fn) [:doc :arglists :const]))
(def texture-wrap! textures/texture-wrap!)
(alter-meta! #'texture-wrap! merge (select-keys (meta #'textures/texture-wrap!) [:doc :arglists :const]))
(def unload-render-texture! textures/unload-render-texture!)
(alter-meta! #'unload-render-texture! merge (select-keys (meta #'textures/unload-render-texture!) [:doc :arglists :const]))
(def unload-texture! textures/unload-texture!)
(alter-meta! #'unload-texture! merge (select-keys (meta #'textures/unload-texture!) [:doc :arglists :const]))
(def update-texture-from-fn! textures/update-texture-from-fn!)
(alter-meta! #'update-texture-from-fn! merge (select-keys (meta #'textures/update-texture-from-fn!) [:doc :arglists :const]))
(def with-render-texture textures/with-render-texture)
(alter-meta! #'with-render-texture merge (select-keys (meta #'textures/with-render-texture) [:doc :arglists :const]))

;; --- util (6) ----------------------------------------------------------
(def base64-encode util/base64-encode)
(alter-meta! #'base64-encode merge (select-keys (meta #'util/base64-encode) [:doc :arglists :const]))
(def compute-crc32 util/compute-crc32)
(alter-meta! #'compute-crc32 merge (select-keys (meta #'util/compute-crc32) [:doc :arglists :const]))
(def compute-md5 util/compute-md5)
(alter-meta! #'compute-md5 merge (select-keys (meta #'util/compute-md5) [:doc :arglists :const]))
(def compute-sha1 util/compute-sha1)
(alter-meta! #'compute-sha1 merge (select-keys (meta #'util/compute-sha1) [:doc :arglists :const]))
(def compute-sha256 util/compute-sha256)
(alter-meta! #'compute-sha256 merge (select-keys (meta #'util/compute-sha256) [:doc :arglists :const]))
(def local-time util/local-time)
(alter-meta! #'local-time merge (select-keys (meta #'util/local-time) [:doc :arglists :const]))
